[package]
name = "dyncall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
libc = "0.2.153"
libffi = "4.1.2"
libloading = "0.8.3"
